# Generated by Django 4.1 on 2022-09-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PythonApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='author',
            new_name='user',
        ),
    ]
